import { Shape } from './types'

export const PUZZLE_SHAPES: Shape[] = [
  { id: 'rose', name: 'Rose', category: 'flora', availableFor: ['couple', 'solo'] },
  { id: 'tulip', name: 'Tulip', category: 'flora', availableFor: ['couple', 'solo'] },
  { id: 'lily', name: 'Lily', category: 'flora', availableFor: ['couple', 'solo'] },
  { id: 'lotus', name: 'Lotus', category: 'flora', availableFor: ['couple', 'solo'] },
  { id: 'sunflower', name: 'Sunflower', category: 'flora', availableFor: ['couple', 'solo', 'children'] },
  { id: 'daisy', name: 'Daisy', category: 'flora', availableFor: ['couple', 'solo', 'children'] },
  { id: 'flower', name: 'Flower', category: 'flora', availableFor: ['couple', 'solo', 'children'] },
  { id: 'maple-leaf', name: 'Maple Leaf', category: 'flora', availableFor: ['couple', 'solo', 'children'] },
  { id: 'oak-leaf', name: 'Oak Leaf', category: 'flora', availableFor: ['couple', 'solo'] },
  { id: 'leaf-simple', name: 'Leaf', category: 'flora', availableFor: ['couple', 'solo', 'children'] },
  { id: 'tree', name: 'Tree', category: 'flora', availableFor: ['couple', 'solo', 'children'] },
  { id: 'pine', name: 'Pine Tree', category: 'flora', availableFor: ['couple', 'solo', 'children'] },
  { id: 'palm', name: 'Palm Tree', category: 'flora', availableFor: ['couple', 'solo'] },
  { id: 'cactus', name: 'Cactus', category: 'flora', availableFor: ['couple', 'solo', 'children'] },
  { id: 'mushroom', name: 'Mushroom', category: 'flora', availableFor: ['couple', 'solo', 'children'] },
  
  { id: 'whale', name: 'Whale', category: 'fauna-sea', availableFor: ['couple', 'solo', 'children'] },
  { id: 'dolphin', name: 'Dolphin', category: 'fauna-sea', availableFor: ['couple', 'solo', 'children'] },
  { id: 'octopus', name: 'Octopus', category: 'fauna-sea', availableFor: ['couple', 'solo'] },
  { id: 'fish', name: 'Fish', category: 'fauna-sea', availableFor: ['couple', 'solo', 'children'] },
  { id: 'seahorse', name: 'Seahorse', category: 'fauna-sea', availableFor: ['couple', 'solo'] },
  { id: 'turtle', name: 'Sea Turtle', category: 'fauna-sea', availableFor: ['couple', 'solo', 'children'] },
  { id: 'starfish', name: 'Starfish', category: 'fauna-sea', availableFor: ['couple', 'solo', 'children'] },
  { id: 'shell', name: 'Shell', category: 'fauna-sea', availableFor: ['couple', 'solo', 'children'] },
  
  { id: 'owl', name: 'Owl', category: 'fauna-sky', availableFor: ['couple', 'solo', 'children'] },
  { id: 'eagle', name: 'Eagle', category: 'fauna-sky', availableFor: ['couple', 'solo'] },
  { id: 'hummingbird', name: 'Hummingbird', category: 'fauna-sky', availableFor: ['couple', 'solo'] },
  { id: 'peacock', name: 'Peacock', category: 'fauna-sky', availableFor: ['couple', 'solo'] },
  { id: 'swan', name: 'Swan', category: 'fauna-sky', availableFor: ['couple', 'solo'] },
  { id: 'penguin', name: 'Penguin', category: 'fauna-sky', availableFor: ['couple', 'solo', 'children'] },
  { id: 'butterfly', name: 'Butterfly', category: 'fauna-sky', availableFor: ['couple', 'solo', 'children'] },
  
  { id: 'cat', name: 'Cat', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  { id: 'dog', name: 'Dog', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  { id: 'fox', name: 'Fox', category: 'fauna-land', availableFor: ['couple', 'solo'] },
  { id: 'rabbit', name: 'Rabbit', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  { id: 'deer', name: 'Deer', category: 'fauna-land', availableFor: ['couple', 'solo'] },
  { id: 'bear', name: 'Bear', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  { id: 'hedgehog', name: 'Hedgehog', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  { id: 'squirrel', name: 'Squirrel', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  { id: 'elephant', name: 'Elephant', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  { id: 'giraffe', name: 'Giraffe', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  { id: 'koala', name: 'Koala', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  { id: 'paw', name: 'Paw Print', category: 'fauna-land', availableFor: ['couple', 'solo', 'children'] },
  
  { id: 'moon', name: 'Moon', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  { id: 'crescent', name: 'Crescent Moon', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  { id: 'sun', name: 'Sun', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  { id: 'star', name: 'Star', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  { id: 'cloud', name: 'Cloud', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  { id: 'rainbow', name: 'Rainbow', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  { id: 'lightning', name: 'Lightning', category: 'celestial', availableFor: ['couple', 'solo'] },
  { id: 'snowflake', name: 'Snowflake', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  { id: 'flame', name: 'Flame', category: 'celestial', availableFor: ['couple', 'solo'] },
  { id: 'raindrop', name: 'Raindrop', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  { id: 'wind', name: 'Wind', category: 'celestial', availableFor: ['couple', 'solo'] },
  { id: 'mountain', name: 'Mountain', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  { id: 'wave', name: 'Wave', category: 'celestial', availableFor: ['couple', 'solo', 'children'] },
  
  { id: 'circle', name: 'Circle', category: 'geometric', availableFor: ['couple', 'solo', 'children'] },
  { id: 'hexagon', name: 'Hexagon', category: 'geometric', availableFor: ['couple', 'solo', 'children'] },
  { id: 'triangle', name: 'Triangle', category: 'geometric', availableFor: ['couple', 'solo', 'children'] },
  { id: 'square', name: 'Square', category: 'geometric', availableFor: ['couple', 'solo', 'children'] },
  { id: 'diamond', name: 'Diamond', category: 'geometric', availableFor: ['couple', 'solo'] },
  { id: 'spiral', name: 'Spiral', category: 'geometric', availableFor: ['couple', 'solo'] },
  { id: 'infinity', name: 'Infinity', category: 'geometric', availableFor: ['couple', 'solo'] },
  
  { id: 'guitar', name: 'Guitar', category: 'creative', availableFor: ['couple', 'solo'] },
  { id: 'piano', name: 'Piano', category: 'creative', availableFor: ['couple', 'solo'] },
  { id: 'music-note', name: 'Music Note', category: 'creative', availableFor: ['couple', 'solo', 'children'] },
  { id: 'microphone', name: 'Microphone', category: 'creative', availableFor: ['couple', 'solo'] },
  { id: 'headphones', name: 'Headphones', category: 'creative', availableFor: ['couple', 'solo'] },
  { id: 'book', name: 'Book', category: 'creative', availableFor: ['couple', 'solo', 'children'] },
  { id: 'pencil', name: 'Pencil', category: 'creative', availableFor: ['couple', 'solo', 'children'] },
  { id: 'palette', name: 'Art Palette', category: 'creative', availableFor: ['couple', 'solo'] },
  { id: 'camera', name: 'Camera', category: 'creative', availableFor: ['couple', 'solo'] },
  { id: 'telescope', name: 'Telescope', category: 'creative', availableFor: ['couple', 'solo'] },
  
  { id: 'coffee', name: 'Coffee', category: 'culinary', availableFor: ['couple', 'solo'] },
  { id: 'cupcake', name: 'Cupcake', category: 'culinary', availableFor: ['couple', 'solo', 'children'] },
  { id: 'ice-cream', name: 'Ice Cream', category: 'culinary', availableFor: ['couple', 'solo', 'children'] },
  { id: 'pizza', name: 'Pizza', category: 'culinary', availableFor: ['couple', 'solo', 'children'] },
  { id: 'cookie', name: 'Cookie', category: 'culinary', availableFor: ['couple', 'solo', 'children'] },
  
  { id: 'house', name: 'House', category: 'structures', availableFor: ['couple', 'solo', 'children'] },
  { id: 'castle', name: 'Castle', category: 'structures', availableFor: ['couple', 'solo', 'children'] },
  { id: 'lighthouse', name: 'Lighthouse', category: 'structures', availableFor: ['couple', 'solo'] },
  { id: 'tent', name: 'Tent', category: 'structures', availableFor: ['couple', 'solo', 'children'] },
  { id: 'windmill', name: 'Windmill', category: 'structures', availableFor: ['couple', 'solo'] },
  
  { id: 'car', name: 'Car', category: 'adventure', availableFor: ['couple', 'solo', 'children'] },
  { id: 'train', name: 'Train', category: 'adventure', availableFor: ['couple', 'solo', 'children'] },
  { id: 'airplane', name: 'Airplane', category: 'adventure', availableFor: ['couple', 'solo', 'children'] },
  { id: 'boat', name: 'Boat', category: 'adventure', availableFor: ['couple', 'solo', 'children'] },
  { id: 'rocket', name: 'Rocket', category: 'adventure', availableFor: ['couple', 'solo', 'children'] },
  { id: 'anchor', name: 'Anchor', category: 'adventure', availableFor: ['couple', 'solo'] },
  { id: 'compass', name: 'Compass', category: 'adventure', availableFor: ['couple', 'solo'] },
  { id: 'hot-air-balloon', name: 'Hot Air Balloon', category: 'adventure', availableFor: ['couple', 'solo', 'children'] },
  { id: 'bicycle', name: 'Bicycle', category: 'adventure', availableFor: ['couple', 'solo', 'children'] },
  { id: 'skateboard', name: 'Skateboard', category: 'adventure', availableFor: ['couple', 'solo', 'children'] },
  
  { id: 'heart', name: 'Heart', category: 'symbols', availableFor: ['couple', 'solo', 'children'] },
  { id: 'crown', name: 'Crown', category: 'treasures', availableFor: ['couple', 'solo'] },
  { id: 'gem', name: 'Gem', category: 'treasures', availableFor: ['couple', 'solo'] },
  { id: 'ring', name: 'Ring', category: 'treasures', availableFor: ['couple', 'solo'] },
  { id: 'key', name: 'Key', category: 'treasures', availableFor: ['couple', 'solo'] },
  { id: 'lock', name: 'Lock', category: 'treasures', availableFor: ['couple', 'solo'] },
  { id: 'hourglass', name: 'Hourglass', category: 'treasures', availableFor: ['couple', 'solo'] },
  { id: 'clover', name: 'Four-Leaf Clover', category: 'symbols', availableFor: ['couple', 'solo', 'children'] },
  { id: 'feather', name: 'Feather', category: 'symbols', availableFor: ['couple', 'solo'] },
]

export const PRICING = {
  couple: 65,
  solo: 65,
  children: 85,
}

export const DEFAULT_COLORS = [
  '#EF4444', '#F97316', '#F59E0B', '#EAB308', '#84CC16',
  '#22C55E', '#10B981', '#14B8A6', '#06B6D4', '#0EA5E9',
  '#3B82F6', '#6366F1', '#8B5CF6', '#A855F7', '#D946EF',
  '#EC4899', '#F43F5E', '#64748B', '#475569', '#1E293B',
]
